code_stack:
  programming_languages:
    - Python: ">=3.8.1,<4.0"
    - PowerShell: "7.0+"
  python_libraries:
    - requests: ">=2.28.1"
    - pyyaml: ">=6.0"
    - python-dotenv: ">=1.0.0"
    - pytest: ">=7.4.0"
    - black: ">=23.0.0"
    - mypy: ">=1.5.0"
  development_tools:
    - Poetry: "Python dependency management"
    - PowerShell: "Cross-platform scripting and automation"
    - pytest: "Testing framework with coverage"
    - Black: "Code formatting"
    - MyPy: "Static type checking"
    - pre-commit: "Git hook management"
  ai_integration:
    - Claude: "Anthropic's Claude AI assistant"
    - Gemini: "Google's Gemini AI model"
    - GitHub_Copilot: "AI pair programming"
